name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn ${{ env.MAVEN_CLI_OPTS }} test
        env:
          MAVEN_OPTS: >-
            -Dhttps.protocols=TLSv1.2
            -Dorg.slf4j.simpleLogger.showDateTime=true
            -Djava.awt.headless=true
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/TEST-*.xml

  oop-exam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create exam directory
        run: mkdir -p target/exam
      - name: Generate diff
        run: git diff vLab HEAD --word-diff src > target/exam/diff.txt
      - name: Generate checksums
        run: |
          sha256sum test/it/polito/po/test/* > target/exam/checks.txt
          sha256sum pom.xml .github/workflows/ci.yml >> target/exam/checks.txt
      - name: Upload exam artifacts
        uses: actions/upload-artifact@v2
        with:
          name: exam
          path: target/exam/*